'use client';
import { useState, useEffect } from 'react';
import { flushSync } from 'react-dom';
import { Activity, ArrowRight, ArrowUpRight, BookOpen, ChartCandlestick, ChevronRight, CircleHelp, Database, FileText, Layers, LayoutDashboard, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Star, TrendingUp, Workflow } from 'lucide-react';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import rawMarket from '@/lib/market.json';
import WorkspacePages from './workspace-pages';

export type Bar={date:string;open:number;close:number;high:number;low:number;amount:number;volume:number};
export type Stock=Bar & {code:string;name:string;market:string;pct:number;history:Bar[]};
export const market=rawMarket as unknown as {date:string;total:number;currentCount:number;staleCount:number;up:number;down:number;flat:number;amount:number;bins:number[];importedAt:string;indices:Stock[];stocks:Stock[]};
export const dateLabel=(d:string)=>`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`;
export const number=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:2});
export const pct=(n:number)=>(n>0?'+':'')+n.toFixed(2)+'%';
export const navItems=[{id:'overview',name:'行情总览',icon:LayoutDashboard},{id:'mainline',name:'主线追踪',icon:TrendingUp},{id:'ladder',name:'涨停与连板',icon:Layers},{id:'selection',name:'策略选股',icon:SlidersHorizontal},{id:'capital',name:'资金透视',icon:Activity},{id:'research',name:'个股研究',icon:ChartCandlestick},{id:'watchlist',name:'我的工作台',icon:Star},{id:'reports',name:'复盘与报告',icon:FileText},{id:'skills',name:'技能中心',icon:Workflow}];
export function Sparkline({bars,color='var(--brand)',large=false}:{bars:Bar[];color?:string;large?:boolean}){const values=bars.map(s=>s.close),min=Math.min(...values),max=Math.max(...values);const pts=values.map((v,i)=>`${i/Math.max(values.length-1,1)*600},${150-(v-min)/(max-min||1)*120}`).join(' ');return <svg className={large?'trend-chart':'sparkline'} viewBox="0 0 600 180" preserveAspectRatio="none" aria-label="本地日线收盘价走势" role="img">{large&&[30,70,110,150].map(y=><line key={y} x1="0" x2="600" y1={y} y2={y} stroke="var(--line)" strokeDasharray="4 5"/>)}<polygon points={`0,180 ${pts} 600,180`} fill={color} opacity=".065"/><polyline points={pts} fill="none" stroke={color} strokeWidth={large?2.4:2} vectorEffect="non-scaling-stroke"/></svg>}
export function Panel({title,children,extra,className=''}:{title:string;children:React.ReactNode;extra?:React.ReactNode;className?:string}){return <section className={'panel '+className}><div className="panel-head"><h2>{title}</h2>{extra}</div>{children}</section>}
export function StockTable({stocks,onSelect,watch=[],onWatch}:{stocks:Stock[];onSelect:(s:Stock)=>void;watch?:string[];onWatch?:(c:string)=>void}) {return <Table><TableHeader><TableRow>{['股票','收盘价','涨跌幅','成交额',...(onWatch?['自选']:[])].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{stocks.map(s=><TableRow key={s.code}><TableCell><button className="stock-name" onClick={()=>onSelect(s)}>{s.name}<small>{s.code}</small></button></TableCell><TableCell className="numeric">{s.close.toFixed(2)}</TableCell><TableCell className={`numeric ${s.pct>=0?'up':'down'}`}>{pct(s.pct)}</TableCell><TableCell className="numeric">{(s.amount/1e8).toFixed(2)} 亿</TableCell>{onWatch&&<TableCell><button className={'star-button '+(watch.includes(s.code)?'saved':'')} aria-label={`${watch.includes(s.code)?'移除':'添加'}自选 ${s.name}`} onClick={()=>onWatch(s.code)}><Star size={16} fill={watch.includes(s.code)?'currentColor':'none'}/></button></TableCell>}</TableRow>)}</TableBody></Table>}
export default function Home(){
 const [page,setPage]=useState('overview'),[chart,setChart]=useState('0'),[selected,setSelected]=useState<Stock|null>(null),[watch,setWatch]=useState<string[]>([]);
 const active=navItems.find(x=>x.id===page),idx=market.indices[Number(chart)]||market.indices[0];
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('zhangcai.watchlist.v1')||'[]');if(Array.isArray(saved))setWatch(saved.filter((v:unknown)=>typeof v==='string'&&market.stocks.some(s=>s.code===v)))}catch{}},[]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{void Promise.resolve(ctx.registerTool({name:'open_stock_snapshot',title:'查看本地股票快照',description:'Open the same stock detail drawer shown by the stock table. Uses historical local data; does not run research or trade.',inputSchema:{type:'object',properties:{code:{type:'string',pattern:'^[0-9]{6}$'}},required:['code'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const v=input as {code?:unknown};if(!v||typeof v.code!=='string'||!/^\d{6}$/.test(v.code)||Object.keys(v).some(k=>k!=='code'))throw new Error('A six digit stock code is required');const s=market.stocks.find(s=>s.code===v.code);if(!s)throw new Error('Stock is absent from the imported same-day snapshot');flushSync(()=>setSelected(s));return {code:s.code,name:s.name,date:s.date,kind:'local_snapshot',researchExecuted:false}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 const toggleWatch=(c:string)=>setWatch(prev=>{const next=prev.includes(c)?prev.filter(x=>x!==c):[...prev,c];try{localStorage.setItem('zhangcai.watchlist.v1',JSON.stringify(next))}catch{}return next});
 const navigate=(id:string)=>setPage(id);
 return <SidebarProvider style={{'--sidebar-width':'218px'} as React.CSSProperties}>
 <Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-symbol"><ChartCandlestick size={23}/></span><div>掌财智能体<small>ZHANGCAI AGENT</small></div></div></SidebarHeader><SidebarContent><div className="nav-label">投研工作空间</div><SidebarMenu>{navItems.map((item,i)=><SidebarMenuItem key={item.id}>{i===7&&<div className="nav-label nav-gap">研究与管理</div>}<SidebarMenuButton isActive={page===item.id} className="nav-item" onClick={()=>navigate(item.id)}><item.icon size={18}/><span>{item.name}</span>{item.id==='skills'&&<small className="count">53</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="engine-box"><span className="engine-dot"/><span>DeepSeek Harness<small>接入规划 · 待联调</small></span></div><button className="settings-link" onClick={()=>navigate('settings')}><Settings2 size={17}/>数据与设置<ChevronRight size={14}/></button><div className="profile"><span className="avatar">掌</span><div>本地研究空间<small>网页 Demo · v0.1</small></div><CircleHelp size={16}/></div></SidebarFooter></Sidebar>
 <div className="app-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger"/><span>工作空间</span><ChevronRight size={14}/><strong>{active?.name||'数据与设置'}</strong></div><div className="top-actions"><span className="preview-tag">PREVIEW</span><span className="top-date">{dateLabel(market.date)}</span><button className="icon-button" aria-label="查看数据状态" onClick={()=>navigate('settings')}><Database size={17}/></button></div></header>
 <main className="workspace"><div className="page-heading"><div><div className="eyebrow">MARKET INTELLIGENCE</div><h1>{active?.name||'数据与设置'}<span className="live-label"><span/>本地行情快照</span></h1><p>从市场全貌出发，让每一次研究都有据可循。</p></div><Button className="primary-button" onClick={()=>navigate('reports')}><Sparkles size={16}/>开始智能复盘<ArrowUpRight size={15}/></Button></div>
 <div className="data-notice"><Database size={14}/><span>读取自 <b>C:/new_tdx_mock</b> · 文件日期 {dateLabel(market.date)} · 日线快照，非实时；数据真实性待核验</span><button onClick={()=>navigate('settings')}>数据说明<ArrowRight size={13}/></button></div>
 {page==='overview'?<><div className="index-grid">{market.indices.map((s,i)=><button key={s.code} className={'index-card '+(Number(chart)===i?'index-active':'')} onClick={()=>setChart(String(i))}><div className="index-name">{s.name}<span>{s.code.toUpperCase()}</span></div><div className="index-value"><strong>{number(s.close)}</strong><span className={s.pct>=0?'up':'down'}>{pct(s.pct)}<ArrowUpRight size={13}/></span></div><Sparkline bars={s.history.slice(-30)} color={s.pct>=0?'var(--up)':'var(--down)'}/><small>日线 · {dateLabel(s.date)}</small></button>)}</div>
 <div className="overview-grid"><div className="overview-left"><Panel title="市场走势" extra={<Tabs value={chart} onValueChange={v=>setChart(String(v))}><TabsList>{market.indices.slice(0,3).map((s,i)=><TabsTrigger key={s.code} value={String(i)}>{s.name.slice(0,3)}</TabsTrigger>)}</TabsList></Tabs>}><div className="chart-summary"><span className="chart-legend"/>{idx?.name}<b>{number(idx?.close||0)}</b><span className={(idx?.pct||0)>=0?'up':'down'}>{pct(idx?.pct||0)}</span><small>近 60 个交易日 · 收盘价</small></div>{idx&&<Sparkline bars={idx.history} large/>}<div className="chart-axis"><span>{idx?dateLabel(idx.history[0].date):''}</span><span>日线走势</span><span>{dateLabel(idx?.date||market.date)}</span></div></Panel>
 <Panel title="市场宽度" extra={<span className="subtle">同日样本 {number(market.currentCount)} 只</span>}><div className="breadth-stats"><div><span>上涨</span><b className="up">{number(market.up)}<small>只</small></b></div><div><span>下跌</span><b className="down">{number(market.down)}<small>只</small></b></div><div><span>平盘</span><b>{market.flat}<small>只</small></b></div><div><span>样本成交额</span><b>{(market.amount/1e12).toFixed(2)}<small>万亿</small></b></div></div><div className="breadth-bar"><span style={{flex:market.up,background:'var(--up)'}}/><span style={{flex:market.flat,background:'#ccd1d9'}}/><span style={{flex:market.down,background:'var(--down)'}}/></div><div className="distribution">{market.bins.map((b,i)=><div key={i}><small>{b}</small><span style={{height:Math.max(3,b/Math.max(...market.bins)*63)+'px',background:i<3?'var(--down)':i===3?'#a8b0bc':'var(--up)',opacity:i===2||i===4?.6:1}}/><label>{['＜−7%','−7~−3%','−3~0%','平盘','0~3%','3~7%','＞7%'][i]}</label></div>)}</div></Panel></div>
 <aside className="insight-rail"><section className="agent-card"><div className="agent-title"><span className="agent-spark"><Sparkles size={19}/></span><strong>掌财观察</strong><span>数据摘要</span></div><h2>先看广度，<br/>再找结构性机会。</h2><p>本地同日样本中，上涨占比 <b>{(market.up/market.currentCount*100).toFixed(1)}%</b>。行情日期和覆盖范围已保留，尚未调用模型生成投研结论。</p><div className="agent-divider"/><div className="check-row"><ShieldCheck size={16}/>保留来源与日期</div><div className="check-row"><Activity size={16}/>情绪与主线研判待接入</div><Button onClick={()=>navigate('research')} className="agent-button">进入个股研究<ArrowRight size={16}/></Button></section><Panel title="研究路径" extra={<Workflow size={16}/>}><div className="workflow-list">{[['01','看市场','情绪周期 · 热点舆情','mainline'],['02','找机会','主线评分 · 策略筛选','selection'],['03','做验证','个股研究 · 风险排雷','research']].map(([n,t,d,p])=><button key={n} onClick={()=>navigate(p)}><span>{n}</span><div><strong>{t}</strong><small>{d}</small></div><ChevronRight size={15}/></button>)}</div></Panel><div className="mini-note"><BookOpen size={17}/><p>53 项股票技能<small>按投研流程组织，保留独立入口</small></p><button aria-label="打开技能中心" onClick={()=>navigate('skills')}><ArrowUpRight size={17}/></button></div></aside></div>
 <div className="bottom-grid"><Panel title="个股涨幅榜" extra={<button className="text-link" onClick={()=>navigate('research')}>全部个股<ArrowRight size={14}/></button>}><StockTable stocks={market.stocks.slice(0,5)} onSelect={setSelected} watch={watch} onWatch={toggleWatch}/></Panel><Panel title="主线观察" extra={<span className="example-label">参考样例 · 09-04</span>}><div className="theme-list">{[['01','养猪','产业催化','7 家涨停'],['02','大消费','政策驱动','7 家涨停'],['03','大农业','期货催化','4 家涨停'],['04','福建自贸','区域主题','5 家涨停']].map(([n,t,d,v])=><button onClick={()=>navigate('mainline')} key={n}><span>{n}</span><div><b>{t}</b><small>{d}</small></div><label>{v}</label><ChevronRight size={14}/></button>)}</div><div className="panel-footnote">来自连板网参考 PDF 的历史样例，与本地行情分开呈现。</div></Panel></div></>:<WorkspacePages key={page} page={page} market={market} onSelect={setSelected} watch={watch} onWatch={toggleWatch} navigate={navigate}/>}
 <footer className="workspace-footer"><span><span className="footer-dot"/>本地行情 · {number(market.total)} 只股票</span><span>研究辅助工具 · 数据与模型输出需独立核验</span><span>掌财智能体 © 2026</span></footer></main></div>
 <Sheet open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><SheetContent className="stock-sheet"><SheetHeader><SheetTitle>{selected?.name} <small>{selected?.code}</small></SheetTitle><SheetDescription>本地日线 · {dateLabel(selected?.date||market.date)} · 未核验交易所原始数据</SheetDescription></SheetHeader>{selected&&<div className="detail-body"><div className="detail-price">{selected.close.toFixed(2)}<span className={selected.pct>=0?'up':'down'}>{pct(selected.pct)}</span></div>{selected.history.length>0&&<Sparkline bars={selected.history} large/>}<div className="detail-grid">{[['开盘',selected.open],['最高',selected.high],['最低',selected.low],['成交额（亿）',selected.amount/1e8]].map(([k,v])=><div key={String(k)}><small>{k}</small><b>{Number(v).toFixed(2)}</b></div>)}</div><Button onClick={()=>toggleWatch(selected.code)}><Star size={15}/>{watch.includes(selected.code)?'移出自选':'加入自选'}</Button><div className="data-notice">技能研究尚未运行；当前只展示行情文件数据。</div></div>}</SheetContent></Sheet>
 </SidebarProvider>
}

