'use client';
import { useState, useMemo } from 'react';
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, Database, Download, FileText, Filter, FolderOpen, Info, Layers, LoaderCircle, Search, ShieldCheck, Sparkles, Star, Target, Workflow, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import skills from '@/lib/skills.json';
import type { Stock } from './page';
type Skill=typeof skills[number];
type Market={date:string;total:number;currentCount:number;staleCount:number;up:number;down:number;flat:number;amount:number;importedAt:string;stocks:Stock[]};
const groupNames:Record<string,string>={selection:'策略选股',mainline:'主线追踪',ladder:'涨停与连板',capital:'资金透视',research:'个股研究',watchlist:'我的工作台',reports:'复盘与报告',settings:'数据与底层能力'};
const themes=[{name:'养猪',count:7,leader:'播恩集团',stage:'3天2板',logic:'全国外三元标猪报价升至 11.09 元 / 公斤',tag:'产业催化',members:['播恩集团','新五丰'],color:'#d7775f'},{name:'大消费',count:7,leader:'百大集团',stage:'2天2板',logic:'7 部门印发推动商品消费扩容升级的实施意见',tag:'政策驱动',members:['百大集团','国芳集团'],color:'#d09c53'},{name:'大农业',count:4,leader:'亚盛集团',stage:'2天2板',logic:'小麦期货创三年新高，农业方向出现回流',tag:'商品涨价',members:['亚盛集团','敦煌种业'],color:'#78976f'},{name:'福建自贸',count:5,leader:'海通发展',stage:'2天2板',logic:'区域主题的板块联动样例，需补充当日催化证据',tag:'区域主题',members:['海通发展','平潭发展'],color:'#6c98a6'}];
const d=(s:string)=>s.slice(0,4)+'-'+s.slice(4,6)+'-'+s.slice(6,8);
const p=(n:number)=>(n>0?'+':'')+n.toFixed(2)+'%';
function Box({title,children,extra}:{title:string;children:React.ReactNode;extra?:React.ReactNode}){return <section className="panel"><div className="panel-head"><h2>{title}</h2>{extra}</div>{children}</section>}
function Tags({list}:{list:string[]}){return <div className="tags">{list.map(t=><span key={t}>{t}</span>)}</div>}
function Empty({title,body}:{title:string;body:string}){return <div className="empty-state"><FolderOpen size={32}/><h3>{title}</h3><p>{body}</p></div>}
export default function WorkspacePages({page,market,onSelect,watch,onWatch,navigate}:{page:string;market:Market;onSelect:(s:Stock)=>void;watch:string[];onWatch:(code:string)=>void;navigate:(id:string)=>void}){
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[skill,setSkill]=useState<Skill|null>(null),[theme,setTheme]=useState(0),[selectedStrategy,setSelectedStrategy]=useState('a-share-15d-selection');
 const [minPct,setMinPct]=useState('3'),[minAmount,setMinAmount]=useState('1'),[filterRan,setFilterRan]=useState(false),[filtered,setFiltered]=useState<Stock[]>([]),[filterError,setFilterError]=useState(''),[report,setReport]=useState(''),[reportBusy,setReportBusy]=useState(false),[pageNo,setPageNo]=useState(0),[sort,setSort]=useState('gain');
 const filteredStocks=useMemo(()=>{let s=market.stocks.filter(x=>`${x.name} ${x.code}`.includes(search.trim()));if(sort==='amount')s.sort((a,b)=>b.amount-a.amount);if(sort==='loss')s.reverse();return s},[market.stocks,search,sort]);
 const related=skills.filter(x=>x.group===page);
 const openById=(id:string)=>setSkill(skills.find(x=>x.id===id)||null);
 function runFilter(){let g=Number(minPct),a=Number(minAmount);if(!minPct.trim()||!minAmount.trim()||!Number.isFinite(g)||!Number.isFinite(a)||g< -100||g>100||a<0){setFilterError('请输入有效条件：涨幅 -100 至 100，成交额不小于 0。');return}setFilterError('');setFiltered(market.stocks.filter(s=>s.pct>=g&&s.amount>=a*1e8));setFilterRan(true)}
 function makeReport(){setReportBusy(true);window.setTimeout(()=>{setReport(`# 掌财智能体 · 本地行情摘要\n\n数据日期：${d(market.date)}\n来源：C:/new_tdx_mock 的 .day 文件\n性质：本地历史快照，原始真实性未独立核验，不代表实时行情。\n\n## 样本概况\n\n- 可读股票：${market.total} 只\n- 同日样本：${market.currentCount} 只；排除旧日期 ${market.staleCount} 只\n- 上涨：${market.up} 只；下跌：${market.down} 只；平盘：${market.flat} 只\n- 上涨占比：${(market.up/market.currentCount*100).toFixed(2)}%\n- 样本成交额：${(market.amount/1e12).toFixed(4)} 万亿元（沪深北样本合计）\n\n## 待完成的投研环节\n\n1. 接入当日市场情绪与热点舆情数据\n2. 核心主线评分，核对新闻、公告与题材\n3. 涨停板深度复盘，检查连板与炸板证据\n4. 风险排雷，通过数据和输出验收后交付\n\n该摘要由页面依据本地数据确定性生成，未调用 DeepSeek Harness，未运行 53 项股票技能，不包含选股建议。`);setReportBusy(false)},350)}
 function download(){const url=URL.createObjectURL(new Blob(['\ufeff'+report],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`掌财行情摘要-${market.date}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function stockTable(stocks:Stock[]){return <Table><TableHeader><TableRow>{['股票','收盘价','涨跌幅','成交额','自选'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{stocks.map(s=><TableRow key={s.code}><TableCell><button className="stock-name" onClick={()=>onSelect(s)}>{s.name}<small>{s.code}</small></button></TableCell><TableCell className="numeric">{s.close.toFixed(2)}</TableCell><TableCell className={s.pct>=0?'up numeric':'down numeric'}>{p(s.pct)}</TableCell><TableCell className="numeric">{(s.amount/1e8).toFixed(2)} 亿</TableCell><TableCell><button className={'star-button '+(watch.includes(s.code)?'saved':'')} onClick={()=>onWatch(s.code)} aria-label={`${watch.includes(s.code)?'移除':'添加'}自选 ${s.name}`}><Star size={16} fill={watch.includes(s.code)?'currentColor':'none'}/></button></TableCell></TableRow>)}</TableBody></Table>}
 function skillCards(list:Skill[]){return <div className="skill-grid">{list.map((s,i)=><button className="skill-card" key={s.id} onClick={()=>setSkill(s)}><div className="skill-card-top"><span className="skill-icon">{i%3===0?<Target size={19}/>:i%3===1?<Layers size={19}/>:<Workflow size={19}/>}</span><small>待适配</small></div><h3>{s.name}</h3><p>{s.note}</p><Tags list={s.dependencies.slice(0,3)}/><div className="skill-card-bottom"><span>{groupNames[s.group]}</span><span>查看技能<ArrowUpRight size={14}/></span></div></button>)}</div>}
 return <div className="secondary-page">
 {page==='skills'&&<><div className="section-intro"><div><h2>把 53 项能力，放进一套研究流程。</h2><p>从权威技能目录读取；根入口存在不等于业务已接通。</p></div><span className="big-count">53<small>项技能</small></span></div><div className="filter-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="搜索技能" placeholder="搜索技能名称、调用别名…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={group} onValueChange={v=>setGroup(v||'all')}><SelectTrigger aria-label="技能分类" className="filter-select"><SelectValue>{group==='all'?'全部分类':groupNames[group]}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">全部分类</SelectItem>{Object.entries(groupNames).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><span className="subtle">{skills.filter(s=>(group==='all'||s.group===group)&&`${s.name} ${s.alias} ${s.id}`.includes(search)).length} 项匹配</span></div>{skillCards(skills.filter(s=>(group==='all'||s.group===group)&&`${s.name} ${s.alias} ${s.id}`.includes(search)))}{!skills.some(s=>(group==='all'||s.group===group)&&`${s.name} ${s.alias} ${s.id}`.includes(search))&&<Empty title="没有匹配技能" body="尝试搜索“龙头”“评分”或切换分类。"/>}</>}
 {page==='mainline'&&<><div className="sample-banner"><Info size={16}/><span>以下题材、龙头与催化来自 2026-09-04 连板网参考 PDF，作为页面样例；并非今日研判。</span></div><div className="theme-grid">{themes.map((t,i)=><button key={t.name} onClick={()=>setTheme(i)} className={'theme-card '+(theme===i?'chosen':'')} style={{'--theme-color':t.color} as React.CSSProperties}><div><span>{t.tag}</span><ArrowUpRight size={16}/></div><h2>{t.name}</h2><p><b>{t.count}</b> 家涨停 <span>{t.leader} · {t.stage}</span></p><div className="theme-meter"><span style={{width:(t.count/7*100)+'%'}}/></div></button>)}</div><div className="two-column"><Box title={`${themes[theme].name} · 题材档案`} extra={<span className="example-label">历史样例</span>}><div className="content-pad"><span className="field-label">驱动逻辑</span><h3 className="logic-title">{themes[theme].logic}</h3><div className="theme-leader"><span>板块龙头</span><b>{themes[theme].leader}</b><label>{themes[theme].stage}</label></div><p className="muted-copy">正式接入后，由核心主线评分与产业链深度研究共同补齐强度、证据来源和失效条件。</p><Button variant="outline" onClick={()=>openById('core-mainline-scoring-system')}>查看核心主线评分<ArrowRight size={15}/></Button></div></Box><Box title="情绪周期观察"><div className="content-pad"><div className="emotion-read"><b>17°</b><span>冰点期<small>参考 PDF · 2026-09-04</small></span></div><div className="emotion-scale"/><div className="scale-labels"><span>冰点</span><span>修复</span><span>发酵</span><span>高潮</span></div><p className="muted-copy">历史样例：封板率 44.8%，炸板率 55.2%。本地日线不能还原盘中封板与炸板，需要补充逐笔或事件数据。</p></div></Box></div><div className="section-label">本页对应技能 <span>{related.length} 项</span></div>{skillCards(related)}</>}
 {page==='ladder'&&<><div className="sample-banner"><Info size={16}/>连板页面参考样例 · 2026-09-04 · 不由本地日线推算完整封板过程</div><div className="metric-grid">{[['涨停家数','39','昨 44'],['连板家数','7','昨 9'],['最高连板','5 板','龙版传媒'],['炸板率','55.2%','参考 PDF']].map(([l,v,n])=><div className="metric-card" key={l}><span>{l}</span><b>{v}</b><small>{n}</small></div>)}</div><Box title="连板天梯" extra={<span className="example-label">历史样例</span>}><div className="ladder"><div><span className="level">5<small>板</small></span><button onClick={()=>openById('a-share-leader-deep-research')}><b>龙版传媒</b><span>AI 应用 · 总龙头</span><small>5天5板<ArrowUpRight size={14}/></small></button></div><div><span className="level muted">2<small>板</small></span>{['百大集团','亚盛集团','海通发展'].map(n=><button key={n} onClick={()=>openById('a-share-limit-up-leader-classification')}><b>{n}</b><span>{n==='百大集团'?'大消费':n==='亚盛集团'?'大农业':'福建自贸'}</span><small>2天2板<ArrowUpRight size={14}/></small></button>)}</div></div><div className="panel-footnote">仅列参考材料中已核对的代表性个股，非完整涨停池。</div></Box><div className="section-label">涨停研究与监控 <span>{related.length} 项技能</span></div>{skillCards(related)}</>}
 {page==='selection'&&<><div className="selection-layout"><Box title="选择策略"><div className="strategy-menu">{skills.filter(s=>s.group==='selection').map(s=><button key={s.id} className={selectedStrategy===s.id?'selected':''} onClick={()=>{setSelectedStrategy(s.id);setFilterRan(false)}}><Target size={15}/>{s.name}{selectedStrategy===s.id&&<Check size={15}/>}</button>)}</div></Box><div><Box title={skills.find(s=>s.id===selectedStrategy)?.name||'策略选股'} extra={<button className="text-link" onClick={()=>openById(selectedStrategy)}>技能说明<ArrowUpRight size={14}/></button>}><div className="content-pad"><div className="sample-banner"><Info size={16}/>此处演示日线基础筛选；所选技能的完整评分和公式尚未执行。</div><div className="form-grid"><label>最小日涨幅（%）<Input type="number" min="-100" max="100" value={minPct} onChange={e=>setMinPct(e.target.value)}/></label><label>最小成交额（亿元）<Input type="number" min="0" value={minAmount} onChange={e=>setMinAmount(e.target.value)}/></label><label>数据范围<div className="readonly-input">沪深北 · {market.currentCount} 只同日样本</div></label></div><div className="action-row"><Button className="primary-button" onClick={runFilter}><Filter size={15}/>运行基础筛选</Button><span className="subtle">{d(market.date)} · 不涉及模型和通达信公式</span></div>{filterError&&<p className="form-error" role="alert">{filterError}</p>}</div></Box><div className="section-spacer"/><Box title={filterRan?`基础条件匹配 · ${filtered.length} 只`:'候选结果'} extra={filterRan?<span className="subtle">展示前 30 只 · 按涨幅排序</span>:undefined}>{filterRan?(filtered.length?stockTable(filtered.slice(0,30)):<Empty title="没有符合条件的股票" body="请调整最小涨幅或成交额，再次运行筛选。"/>):<Empty title="设置条件，查看本地样本" body="结果可以加入自选；完整技能结论需要后续 Harness 接入与数据验证。"/>}</Box></div></div></>}
 {page==='capital'&&<><div className="sample-banner"><Info size={16}/>资金净流入、游资席位和机构持仓无法由普通日线成交额替代。该页展示真实依赖与技能入口。</div><Tabs defaultValue="lhb"><TabsList><TabsTrigger value="lhb">龙虎榜</TabsTrigger><TabsTrigger value="youzi">游资追踪</TabsTrigger><TabsTrigger value="institution">机构与庄家</TabsTrigger></TabsList><TabsContent value="lhb"><Box title="龙虎榜资金席位"><Empty title="等待龙虎榜数据源" body="正式接入后展示买卖席位、净买额、集中度与资金持续性；不把成交额标为净流入。"/></Box></TabsContent><TabsContent value="youzi"><Box title="游资追踪"><Empty title="等待席位映射与 TQ 资金公式" body="需要核验 L2 数据授权、通达信公式及席位身份后，才能输出游资资金判断。"/></Box></TabsContent><TabsContent value="institution"><Box title="机构与庄家资金"><Empty title="等待本机公式与 TQ 验证" body="读取本机已安装公式，保留公式名称、数据日期和原始值；当前不模拟计算。"/></Box></TabsContent></Tabs><div className="section-label">资金研究技能 <span>{related.length} 项</span></div>{skillCards(related)}</>}
 {page==='research'&&<><div className="filter-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="搜索本地股票" placeholder="输入股票代码或名称，开始研究" value={search} onChange={e=>{setSearch(e.target.value);setPageNo(0)}}/></div><Select value={sort} onValueChange={v=>{setSort(v||'gain');setPageNo(0)}}><SelectTrigger aria-label="个股排序" className="filter-select"><SelectValue>{sort==='gain'?'涨幅优先':sort==='loss'?'跌幅优先':'成交额优先'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="gain">涨幅优先</SelectItem><SelectItem value="loss">跌幅优先</SelectItem><SelectItem value="amount">成交额优先</SelectItem></SelectContent></Select><span className="subtle">{filteredStocks.length} 只匹配</span></div><Box title="个股档案" extra={<span className="subtle">点击股票查看行情详情</span>}>{filteredStocks.length?stockTable(filteredStocks.slice(pageNo*15,pageNo*15+15)):<Empty title="没有找到这只股票" body="可按六位代码或中文名称检索当前同日样本。"/>}{filteredStocks.length>0&&<div className="pagination-row"><span>第 {pageNo+1} / {Math.ceil(filteredStocks.length/15)} 页</span><Button variant="outline" disabled={!pageNo} onClick={()=>setPageNo(v=>v-1)}>上一页</Button><Button variant="outline" disabled={(pageNo+1)*15>=filteredStocks.length} onClick={()=>setPageNo(v=>v+1)}>下一页</Button></div>}</Box><div className="section-label">研究工具 <span>{related.length} 项技能</span></div>{skillCards(related)}</>}
 {page==='watchlist'&&<><Tabs defaultValue="watch"><TabsList><TabsTrigger value="watch">我的自选 · {watch.length}</TabsTrigger><TabsTrigger value="holdings">持仓监控</TabsTrigger><TabsTrigger value="journal">研究日志</TabsTrigger></TabsList><TabsContent value="watch"><Box title="自选观察池" extra={<Button variant="outline" onClick={()=>navigate('research')}><Search size={14}/>添加股票</Button>}>{watch.length?stockTable(market.stocks.filter(s=>watch.includes(s.code))):<Empty title="把关注的股票放到这里" body="在首页榜单、策略筛选或个股研究中，点击星标加入自选。自选仅保存在当前浏览器。"/>}</Box></TabsContent><TabsContent value="holdings"><Box title="持仓股监控"><Empty title="尚未导入持仓" body="正式版需要成本价、数量、行情源及告警服务。当前 Demo 未启动后台监控。"/></Box></TabsContent><TabsContent value="journal"><Box title="研究日志"><Empty title="还没有研究记录" body="正式接入后，记录技能、数据日期、运行状态、证据和报告。"/></Box></TabsContent></Tabs><div className="section-label">工作台技能</div>{skillCards(related)}</>}
 {page==='reports'&&<><div className="report-layout"><div><Box title="智能复盘流程" extra={<span className="example-label">流程预览</span>}><div className="report-flow">{[['01','短线市场情绪','判断情绪阶段与市场广度'],['02','核心主线评分','核对题材强度与事件催化'],['03','涨停板深度复盘','研究龙头、梯队与风险'],['04','投研交付与验收','保留证据，验收文档结果']].map(([n,t,b])=><div key={n}><span>{n}</span><section><b>{t}</b><small>{b}</small></section><label>待接入</label></div>)}</div><div className="content-pad"><Button className="primary-button" disabled={reportBusy} onClick={makeReport}>{reportBusy?<LoaderCircle className="spin" size={16}/>:<FileText size={16}/>}生成本地行情摘要</Button><p className="muted-copy">可立即生成已读取行情的 Markdown 摘要。上方完整技能链尚未运行，摘要不含模型分析。</p></div></Box></div><Box title="报告预览" extra={report?<Button variant="outline" onClick={download}><Download size={15}/>下载摘要</Button>:undefined}>{report?<pre className="report-preview">{report}</pre>:<Empty title="让研究结果可追溯" body="生成摘要后在这里查看，确认数据日期、样本数及待完成环节。"/>}</Box></div><div className="section-label">复盘、写作与交付 <span>{related.length} 项技能</span></div>{skillCards(related)}</>}
 {page==='settings'&&<><div className="two-column"><Box title="本地数据源"><div className="content-pad"><div className="source-status"><Database size={25}/><div><b>通达信日线</b><small>已读取为网页静态快照</small></div><span className="status-good">已导入</span></div><dl className="settings-list"><div><dt>行情位置</dt><dd>C:/new_tdx_mock</dd></div><div><dt>解析格式</dt><dd>.day · 32 字节 / 记录</dd></div><div><dt>证券名称</dt><dd>.tnf · 360 字节 / 记录</dd></div><div><dt>最新文件日期</dt><dd>{d(market.date)}</dd></div><div><dt>股票覆盖</dt><dd>{market.total} 只 · 同日 {market.currentCount} 只</dd></div><div><dt>旧日期文件</dt><dd>{market.staleCount} 只 · 已排除汇总</dd></div><div><dt>导入时间</dt><dd>{market.importedAt.replace('T',' ')}</dd></div></dl><p className="muted-copy">网页使用导入快照，不会自动读取电脑磁盘。目录名含 mock，尚未与交易所原始数据独立核验。涨跌幅按相邻日线收盘价计算，未做除权校验。</p></div></Box><Box title="DeepSeek Harness"><div className="content-pad"><div className="source-status"><Workflow size={25}/><div><b>DeepSeek Harness</b><small>基座接入方案</small></div><span className="example-label">待联调</span></div><dl className="settings-list"><div><dt>用户提供的包</dt><dd>@deepseek-ai/dsh</dd></div><div><dt>启动方式</dt><dd>npx @deepseek-ai/dsh web</dd></div><div><dt>股票能力</dt><dd>53 项技能 · 53 个根入口</dd></div><div><dt>现有插件</dt><dd>查目录、读取技能说明</dd></div><div><dt>真实业务执行</dt><dd>需要补充适配层</dd></div><div><dt>当前模型会话</dt><dd>未连接</dd></div><div><dt>账户密钥</dt><dd>Demo 不收集或保存</dd></div></dl><p className="muted-copy">正式版用独立研究配置管理工具、会话、技能执行与日志。桌面程序负责启动本地服务，浏览器界面只访问受控接口。</p></div></Box></div><Box title="Windows 安装包方案"><div className="package-plan"><div><FolderOpen size={27}/><h3>掌财智能体 Setup.exe</h3><p>桌面界面、固定版本 Harness、技能适配层、Python 运行环境。</p></div><ArrowRight size={24}/><div><Database size={27}/><h3>掌财智能体 Data.exe</h3><p>可选历史数据与缓存，独立版本、校验与更新，复用用户本地通达信。</p></div></div><div className="panel-footnote">当前交付为网页 Demo 和可行性研究，尚未构建新的 Windows 安装包。</div></Box><div className="section-label">系统与数据能力 <span>{related.length} 项</span></div>{skillCards(related)}</>}
 <Sheet open={!!skill} onOpenChange={v=>!v&&setSkill(null)}><SheetContent className="skill-sheet"><SheetHeader><SheetTitle>{skill?.name}</SheetTitle><SheetDescription>权威目录中的独立股票技能 · 待适配</SheetDescription></SheetHeader>{skill&&<div className="content-pad"><div className="skill-detail-id">{skill.id}</div><h3 className="detail-title">使用范围</h3><p className="muted-copy">{skill.note}</p><h3 className="detail-title">中文调用名称</h3><p className="muted-copy">{skill.alias}</p><h3 className="detail-title">主要依赖提示</h3><Tags list={skill.dependencies}/><h3 className="detail-title">执行路径</h3><div className="execution-chain"><span>Harness 工具</span><ChevronRight size={14}/><span>技能适配层</span><ChevronRight size={14}/><span>根入口</span></div><p className="muted-copy">保留 {skill.entry}。依赖提示来自材料静态分析，完整要求以工作流与执行合同为准。</p><div className="sample-banner"><ShieldCheck size={17}/>当前只查看技能信息。未运行模型、Python 技能或后台监控。</div><Button className="primary-button" onClick={()=>{navigate(skill.group);setSkill(null)}}>前往{groupNames[skill.group]}<ArrowRight size={15}/></Button></div>}</SheetContent></Sheet>
 </div>
}

